os:
- linux
dist: xenial

language:
- c
env:
  global:
  - CI_TOOLS="$TRAVIS_BUILD_DIR/tools/travis"
  - PLATFORM="$(uname)"
  - NINJA_NETFILE="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip"
  - NINJA_PATH="${CI_TOOLS}/ninja"
  - COVERITY_BUILD_PATH="${TRAVIS_BUILD_DIR}/cov_build"
  - PROJECT_SCRIPT="${TRAVIS_BUILD_DIR}/run.py"
  - FILE_RSA="${CI_TOOLS}/id_rsa"
  - secure: QRORzlDpl1W4JVYKCuZvLmoY49ZNu+dLm/fFp+jG/69cZ7rD1W68TFLD4Hje7Wu4VN/Tc0/AYpgqQgbD1OtBlshjczwSr+fxOuHHbV4vZ5F2Xxkf35jS0saefFhymlRGZKZG7M8cLhc9wRu60IdpzqqyIX/A4zXVIDxzg3Sr1hsDQ7bgLdXGiLWDtsoMFh2l8BaILeD/yN1MQrJMNVAunvg8LVq0CKSn7t7vPbScbo0g+F3W/CPopH0486LSnTWNncFhdFHHkw+0/JKpfj2yyUBoSXzb5C/g9CXSLUaPr2KnGlCZEpXz1A3C8eZHHqLx9lNYM7K9gHx4guDHcaboy9M3RHFQ+J+yOf1ci0yUzUl+jn4PhM8RhHOpUidOBw6PkyyHoC2jXO1LsW8fp+OX2cvWQiNwJ6LEEcH3tikNbG4dh3pjmTPzDVLGEVtROSfBOk3Fnsr8x7y9bYjAw8cp9Wjf6jJgyu9u6HXEFiaoGM4GnEp0XFGx60ul6h5McHoZo5nmvmYvju4Lwlt2OzAxE3Ano8XfSlRIH5pyk7KRtjtQWCQgufQ1xrCz4GZr98ATMornLGtxOc72kEXhXH+2Cug2Aqmbf0UspBr3U/FV8+X2aq364+gEduZOohm9u1uTcbU+ZWuL9KECU/hQ/TaVH5Ix4MY/nQpGsv+oMFnMGvM=
branches:
  only:
  - master
  - release
  - coverity
addons:
  apt:
    packages:
# for meson support
    - python3 python3-setuptools python3-pip
# need utilites
    - tar unzip xz-utils fakeroot cmake
# headers and dependencies
    - libcunit1-dev libucl-dev libncurses5-dev libncursesw5-dev
      libx11-dev libxaw7-dev libxmu-dev libxt-dev libsm-dev
      libice-dev libxext-dev libxpm-dev

  coverity_scan:
    project:
      name: SkyMaverick/UniChatMod 
      version: 0.1

    notification_email: skymaverickas@gmail.com
    build_command_prepend: meson ${TRAVIS_BUILD_DIR} ${COVERITY_BUILD_PATH}
    build_command: ninja -C ${COVERITY_BUILD_PATH}
    branch_pattern: coverity
  
before_install:
# get ninja build system
- wget $NINJA_NETFILE && unzip -q ninja-linux.zip -d $NINJA_PATH
- export PATH="$NINJA_PATH:$PATH"

# install meson
- sudo python3 -m pip install --upgrade pip
- sudo python3 -m pip install meson

script:
- case "${TRAVIS_BRANCH}" in
      master)
          ${PROJECT_SCRIPT} debug
      ;;
      release)
          ${PROJECT_SCRIPT} release
      ;; esac
after_success:
# create packages
-  ${PROJECT_SCRIPT} pack_arc
-  ${PROJECT_SCRIPT} pack_deb
-  ${PROJECT_SCRIPT} pack_sh

-  ${CI_TOOLS}/sfupload.sh ${TRAVIS_BUILD_DIR}
