# language: c
# sudo: required
# matrix:
sudo: false

os:
  - linux

language:
  - c

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull skymaverick/meson-ucm:xenial; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        echo FROM skymaverick/meson-ucm:xenial >> Dockerfile;
        echo ADD . /root >> Dockerfile;
        docker build -t ucmbuild:single .;
        docker run -t ucmbuild:single /bin/sh -c "cd /root && ./build.sh debug"; 
    fi
