#ifndef _UNICHAT_LEGACY_PROTOCOL_H_
#define _UNICHAT_LEGACY_PROTOCOL_H_

enum {
    UCL_USERSTAT_ACTIVE = 0,
    UCL_USERSTAT_BUSY = 1,
    UCL_USERSTAT_GAME = 2,
    UCL_USERSTAT_NOTALLOW = 3,
    UCL_USERSTAT_NCONNECT = 4,
};

#endif
